spring.application.name=Smart Waste Management

spring.datasource.url=jdbc:mysql://localhost:3306/smart_waste_db
spring.datasource.username=root
spring.datasource.password=Pr@deep07
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=smartwastemanagement11-production.up.railway.app
server.address=0.0.0.0